# Generated by Django 3.0.6 on 2020-06-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='creator',
            new_name='owner',
        ),
    ]
