# Generated by Django 3.0.6 on 2020-06-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_id',
            new_name='id',
        ),
    ]
