# Generated by Django 3.0.6 on 2020-06-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200627_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='athlete',
            new_name='user',
        ),
    ]
